services:
  - type: web
    name: friendly-chat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 server:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
